name: Code Report
description: Report an Update to Code
labels: ["type: Code"]
body:
  - type: markdown
    attributes:
      value: |
        ## About this form
        This form is only for tracking developer-focussed actions, such as 
        refactoring, dependency updates and similar.
        Rarely, these might be used to gauge user data.
  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: What is the scope of the change and why is it needed?
    validations:
      required: true

  - type: textarea
    id: discovery
    attributes:
      label: Discovery
      description: |
        What will be changed?.
    validations:
      required: true

  - type: textarea
    id: validation
    attributes:
      label: Validate
      description: |
        What was your environment you tested these changes in?
        Do any new dependencies need to be added?
        Any other pertinent information?
    validations:
      required: true
